server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# ============================================================
# ChatModel
# ============================================================
llm:
  provider: ${LLM_PROVIDER:zhipu}
  zhipu:
    base-url: https://open.bigmodel.cn/
    api-key: ${ZHIPU_API_KEY:}
    model-name: glm-4-flash
  deepseek:
    base-url: https://api.deepseek.com
    api-key: ${DEEPSEEK_API_KEY:}
    model-name: deepseek-chat

# ============================================================
# RAG Configuration
# ============================================================
rag:
  # Document chunk size. (number of characters)
  chunk-size: 500
  # Overlap size.
  chunk-overlap: 100
  # The maximum number of retrieval segments result.
  max-results: 5

# ============================================================
# Session Configuration
# ============================================================
chat:
  # The maximum number of left message each session. (The messages that out of the maximum  will be dropped)
  max-memory-messages: 20

# ============================================================
# Logging Configuration
# ============================================================
logging:
  level:
    dev.langchain4j: DEBUG
    com.smartdoc: DEBUG
